1. What is a Python library? Why ^o we use Python libraries?
2. What is the ^ifference between Numpy array an^ List?
3. Fin^ the shape, size an^ ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
4. Write python co^e to access the first row of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
7. How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?
8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?
9. Write co^e to increase the ^imension of the following array?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
10. How to transpose the following array in NumPy?
[[1, 2, 3, 4]
[5, 6, 7, 8],
[9, 10, 11, 12]]
11. Consi^er the following matrix:
Matrix A2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Matrix B2 [[1, 2, 3, 4] [5, 6, 7, 8],[9, 10, 11, 12]]
Perform the following operation using Python1
,+ I(dex wiLe multiplicatio'
]+ Matix multiplicatio'
+ Add both the maticK
-+ Subtact matix B om 
+ Diide Matix B by A
12. Which function in Numpy can be use^ to swap the byte or^er of an array?
13. What is the significance of the np.linalg.inv function?
14. What ^oes the np.reshape function ^o, an^ how is it use^?
15. What is broa^casting in Numpy?

A Python library is a collection of pre-written code and functionalities that can be imported and used in your Python programs. Libraries provide ready-to-use functions and classes that help you perform specific tasks without having to write the code from scratch. We use Python libraries to save time, improve code readability, and leverage the expertise of other developers who have written efficient and tested code.

NumPy arrays are similar to Python lists but have some key differences:
NumPy arrays are homogeneous, meaning they can only store elements of the same data type, whereas lists can store elements of different data types.
NumPy arrays offer more efficient storage and operations for numerical computations compared to lists.
NumPy arrays support vectorized operations, which can significantly speed up computations compared to using loops with lists.
NumPy arrays have attributes like shape, size, and dimension, which provide information about the array structure.

In [1]:
import numpy as np

arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print("Shape:", arr.shape)
print("Size:", arr.size)
print("Dimension:", arr.ndim)


Shape: (3, 4)
Size: 12
Dimension: 2


In [2]:
first_row = arr[0]
print(first_row)


[1 2 3 4]


In [3]:
element = arr[2, 3]
print(element)


12


In [4]:
odd_indexed_elements = arr[:, 1::2]  # Start from index 1 and take every second element
print(odd_indexed_elements)


[[ 2  4]
 [ 6  8]
 [10 12]]


In [5]:
random_matrix = np.random.rand(3, 3)
print(random_matrix)


[[0.25654687 0.09144552 0.91419229]
 [0.70669042 0.56913804 0.17261207]
 [0.39501275 0.26456864 0.72182551]]


np.random.rand generates random numbers from a uniform distribution between 0 and 1.
np.random.randn generates random numbers from a standard normal distribution (mean 0, standard deviation 1).

In [6]:
increased_dimension = np.expand_dims(arr, axis=0)
print(increased_dimension.shape)


(1, 3, 4)


In [7]:
transposed_array = arr.T
print(transposed_array)


[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [ ]:
index_wise_multiplication = arr * arr  # Element-wise multiplication
matrix_multiplication = np.dot(arr, arr.T)  # Matrix multiplication
additionsubtraction = arr - arr
 = arr + arr
division = arr / arr
    


The np.ndarray.byteswap() function can be used to swap the byte order of an array in NumPy.

The np.linalg.inv function in NumPy is used to compute the inverse of a square matrix. It is particularly useful in linear algebra and solving systems of linear equations.

reshaped_array = np.reshape(arr, (2, 6))  # Reshape to a 2x6 array


Broadcasting in NumPy refers to the ability of NumPy to perform element-wise operations between arrays of different shapes and sizes. NumPy automatically adjusts the dimensions of the arrays to make the operation valid, which simplifies code and improves performance.